name: CI/CD to EC2 via Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3️⃣ Build & push image
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/ts-demo:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 4️⃣ Decode SSH key
      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # 5️⃣ Deploy on EC2
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: private_key.pem
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/ts-demo:latest
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull $IMAGE
            docker stop ts-demo || true
            docker rm ts-demo || true
            docker run -d -p 8000:8000 --env-file /home/ubuntu/.env --name ts-demo $IMAGE
